language: cpp
os: linux
dist: focal
sudo: false

branches:
  only:
  - master

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_script:
  - sudo apt update -qq
# - sudo apt-get install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build libglib2.0-dev libpixman-1-dev
  - wget https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2022.03.09/riscv64-elf-ubuntu-20.04-nightly-2022.03.09-nightly.tar.gz
  - tar xf riscv64-elf-ubuntu-20.04-nightly-2022.03.09-nightly.tar.gz
  - export RISCV=$(pwd)/riscv/bin/

script:
  - make -j 4 RISCVPATH=$RISCV
